trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest


services:
  languagetool:
    image: erikvl87/languagetool:6.5
    ports:
    - 8010:8010

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    addToPath: true

- script: |
    python -m pip install uv
    uv sync
  displayName: Install dependencies

- script: uv run python tests/integration/azure_test_intakes.py
  displayName: Run test_intake.py
  env:
    SURVEY_IDS: $(SURVEY_IDS)
    REDCAP_API_TOKEN: $(REDCAP_API_TOKEN)
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    LANGUAGE_TOOL_URL: http://localhost:8010/v2
    AZURE_BLOB_CONNECTION_STRING: unused
    AZURE_OPENAI_API_KEY: unused
    AZURE_OPENAI_LLM_DEPLOYMENT: unused
    AZURE_OPENAI_ENDPOINT: unused
