trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    addToPath: true
- task: PythonScript@0
  displayName: 'Create test_intake.py'
  env:
    SUBJECT_1: $(SUBJECT_1)
  inputs:
    scriptSource: 'inline'
    script: |
      with open('test_intake.py', 'w') as f:
          f.write('import asyncio\n')
          f.write('from ctk_functions.functions.intake import controller as intake_controller\n')
          f.write('survey_id = "$(SUBJECT_1)"\n')
          f.write('asyncio.run(\n')
          f.write('    intake_controller.get_intake_report(\n')
          f.write('        survey_id, "anthropic.claude-3-5-sonnet-20240620-v1:0"\n')
          f.write('    )\n')
          f.write(')\n')
- script: |
    python -m pip install poetry
    poetry install
  displayName: 'Install dependencies'

- script: poetry run python test_intake.py
  displayName: 'Run test_intake.py'
  env:
    REDCAP_API_TOKEN: $(REDCAP_API_TOKEN)
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    AZURE_BLOB_CONNECTION_STRING: unused
    AZURE_OPENAI_API_KEY: unused
    AZURE_OPENAI_LLM_DEPLOYMENT: unused
    AZURE_OPENAI_ENDPOINT: unused