name: Trigger Build Workflow

permissions:
  contents: read

on:
  workflow_run:
    workflows: [Python Tests]
    types:
    - completed

jobs:
  dispatch:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch
      uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0
      with:
        token: ${{ secrets.CTK_BUILD_PAT }}
        repository: childmindresearch/ctk-build
        event-type: dependency_updated
        client-payload: '{"triggered_by": "${{ github.repository }}, on push event", "commit_sha": "${{ github.sha }}", "branch": "${{ github.ref }}"}'
